version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: 'rabbitmq'
    hostname: rabbitmq
    environment:
      - "RABBITMQ_DEFAULT_PASS=guest"
      - "RABBITMQ_DEFAULT_USER=guest"
    logging:
      driver: none
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq.mnesia"
    networks:
      - mynetwork
  # app: 
  #   container_name: credit-score
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/usr/src/app
  #   environment:
  #     - PORT=3000
  #     - MONGO_CONNECTION_STRING=mongodb://mongodb:27017/credit-score
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - mynetwork
  #   depends_on:
  #     - mongodb

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

volumes:
  mongodb_data: